// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AttachmentsComponent: typeof import('./src/components/AttachmentsComponent.vue')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    CourseCard: typeof import('./src/components/CourseCard.vue')['default']
    DialogModal: typeof import('./src/components/DialogModal.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PreviewImg: typeof import('./src/components/PreviewImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
